# site settings
title: Kry9toN
subtitle:
email: dhimasbagusprayoga@gmail.com
description: User android and Linux, Owner custom rom android and custom kernel android
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Kry9toN
street_address:
city: Blitar
state: Jawa timur
zip_code: 66155
country: Indonesia

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url: https://github.com/kry9ton
instagram_url: https://instagram.com/dhimasbpy
telegram_url: https://t.me/kry9ton
# build settings
markdown: kramdown

kramdown:
  input: GFM

sass:
  style: compressed

include: ["_pages"]
collections:
  pages:
    output: true
    permalink: :path

permalink: pretty
permalink: /:title/
