# site settings
title: KangLiham
subtitle:
email: beatone25@gmail.com
description: User android and Linux, Owner custom rom android and custom kernel android
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Kang Liham
street_address:
city: Kawali
state: Jawa Barat
zip_code: 46253
country: Indonesia

# homepage tiles
tiles-source: posts # accepts "posts" or "pages"
tiles-count: 6

# social settings
github_url: https://github.com/IlhamXM
instagram_url: https://instagram.com/liham_xm
telegram_url: https://t.me/XV_LXM
# build settings
markdown: kramdown

kramdown:
  input: GFM

sass:
  style: compressed

include: ["_pages"]
collections:
  pages:
    output: true
    permalink: :path

permalink: pretty
permalink: /:title/
